import { FaArrowLeft } from "react-icons/fa";
import { FaArrowRight } from "react-icons/fa";
import { FaPlay } from "react-icons/fa";
import { FaLinkedin } from "react-icons/fa6";
import { FaSpotify } from "react-icons/fa";
import { MdOutlinePause } from "react-icons/md";
import { CiLocationOn } from "react-icons/ci";
import { FaPhoneAlt } from "react-icons/fa";
import { HiMiniSpeakerWave } from "react-icons/hi2";
import { HiMiniSpeakerXMark } from "react-icons/hi2";
import { MdSkipNext } from "react-icons/md";
import { MdSkipPrevious } from "react-icons/md";
import { CiSearch } from "react-icons/ci";

export const leftArrow = <FaArrowLeft />;
export const rightArrow = <FaArrowRight />;
export const play = <FaPlay />;
export const pause = <MdOutlinePause />;
export const sound = <HiMiniSpeakerWave />;
export const mute = <HiMiniSpeakerXMark />;
export const next = <MdSkipNext />;
export const prev = <MdSkipPrevious />;
export const linkedIn = <FaLinkedin size={35} color="white" />;
export const spotify = <FaSpotify size={35} color="white" />;
export const location = <CiLocationOn size={30} />;
export const phone = <FaPhoneAlt size={17} />;
export const search = <CiSearch />;
